//! Global 1-degree gridded ocean/weather field, sampled per voyage tick by lat/lon.
//!
//! Replaces the premade per-leg `OceanConditions` with a position-driven field
//! generated by `tools/generate_ocean_grid.py` (real NOAA OISST sea-surface
//! temperature plus a physically-grounded climatology for the rest). The file is
//! a little-endian binary blob (`data/ocean_grid.bin`, ~2 MB) loaded once and
//! bilinearly interpolated, so conditions vary continuously along any route.

use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use crate::environment::ocean::OceanConditions;

const MAGIC: &[u8; 8] = b"OCGRID02";

// Variable plane order — must match VARS in tools/generate_ocean_grid.py.
const VAR_HS: usize = 0;
const VAR_TP: usize = 1;
const VAR_GAMMA: usize = 2;
const VAR_TEMP: usize = 3;
const VAR_SALINITY: usize = 4;
const VAR_PH: usize = 5;
const VAR_WIND: usize = 6;
const VAR_SLAM: usize = 7;

#[derive(Debug)]
pub struct OceanGrid {
    nlat: usize,
    nlon: usize,
    lat0: f64,
    lon0: f64,
    dlat: f64,
    dlon: f64,
    /// `nvars` contiguous planes, each `nlat * nlon`, row-major (row = latitude).
    data: Vec<f32>,
}

impl OceanGrid {
    pub fn load(path: &Path) -> Result<Self, String> {
        let bytes = std::fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
        if bytes.len() < 8 + 12 + 32 || &bytes[0..8] != MAGIC {
            return Err(format!("{}: bad magic/header", path.display()));
        }
        let i32_at = |off: usize| i32::from_le_bytes(bytes[off..off + 4].try_into().unwrap());
        let f64_at = |off: usize| f64::from_le_bytes(bytes[off..off + 8].try_into().unwrap());

        let nlat = i32_at(8) as usize;
        let nlon = i32_at(12) as usize;
        let nvars = i32_at(16) as usize;
        let lat0 = f64_at(20);
        let lon0 = f64_at(28);
        let dlat = f64_at(36);
        let dlon = f64_at(44);

        let header = 8 + 12 + 32;
        let expected = nvars * nlat * nlon;
        let floats = &bytes[header..];
        if floats.len() < expected * 4 {
            return Err(format!(
                "{}: truncated ({} floats, need {})",
                path.display(),
                floats.len() / 4,
                expected
            ));
        }
        let mut data = Vec::with_capacity(expected);
        for i in 0..expected {
            let o = i * 4;
            data.push(f32::from_le_bytes(floats[o..o + 4].try_into().unwrap()));
        }

        Ok(Self { nlat, nlon, lat0, lon0, dlat, dlon, data })
    }

    fn at(&self, var: usize, row: usize, col: usize) -> f64 {
        self.data[var * self.nlat * self.nlon + row * self.nlon + col] as f64
    }

    /// Bilinearly interpolate one variable. Latitude is clamped to the poles;
    /// longitude wraps around the antimeridian.
    fn sample_var(&self, var: usize, lat_deg: f64, lon_deg: f64) -> f64 {
        let fr = (lat_deg - self.lat0) / self.dlat;
        let r_floor = fr.floor();
        let tr = (fr - r_floor).clamp(0.0, 1.0);
        let r0 = (r_floor as isize).clamp(0, self.nlat as isize - 1) as usize;
        let r1 = (r0 + 1).min(self.nlat - 1);

        let fc = (lon_deg - self.lon0) / self.dlon;
        let c_floor = fc.floor();
        let tc = (fc - c_floor).clamp(0.0, 1.0);
        let nlon = self.nlon as isize;
        let c0 = (c_floor as isize).rem_euclid(nlon) as usize;
        let c1 = ((c_floor as isize + 1).rem_euclid(nlon)) as usize;

        let v00 = self.at(var, r0, c0);
        let v01 = self.at(var, r0, c1);
        let v10 = self.at(var, r1, c0);
        let v11 = self.at(var, r1, c1);
        let top = v00 * (1.0 - tc) + v01 * tc;
        let bot = v10 * (1.0 - tc) + v11 * tc;
        top * (1.0 - tr) + bot * tr
    }

    /// Full conditions at a position. `encounter_angle_deg` is vessel-relative
    /// (heading vs. swell) and is not a gridded field, so the caller supplies it.
    pub fn sample(&self, lat_deg: f64, lon_deg: f64, encounter_angle_deg: f64) -> OceanConditions {
        OceanConditions {
            hs_m: self.sample_var(VAR_HS, lat_deg, lon_deg),
            tp_s: self.sample_var(VAR_TP, lat_deg, lon_deg),
            jonswap_gamma: self.sample_var(VAR_GAMMA, lat_deg, lon_deg),
            encounter_angle_deg,
            water_temp_c: self.sample_var(VAR_TEMP, lat_deg, lon_deg),
            salinity_ppt: self.sample_var(VAR_SALINITY, lat_deg, lon_deg),
            ph: self.sample_var(VAR_PH, lat_deg, lon_deg),
            wind_speed_ms: self.sample_var(VAR_WIND, lat_deg, lon_deg),
            slam_probability: self.sample_var(VAR_SLAM, lat_deg, lon_deg),
        }
    }
}

fn candidate_paths() -> Vec<PathBuf> {
    let mut paths = vec![PathBuf::from("data/ocean_grid.bin")];
    if let Ok(exe) = std::env::current_exe() {
        // target/release/seaforge_v2 -> project root is three levels up.
        for up in [1usize, 2, 3, 4] {
            let mut p = exe.clone();
            for _ in 0..up {
                p.pop();
            }
            paths.push(p.join("data/ocean_grid.bin"));
        }
    }
    paths
}

/// Process-wide grid, loaded lazily. Returns `None` if the file is missing or
/// `SEAFORGE_OCEAN_GRID=0` is set (forcing the legacy per-leg conditions).
pub fn global() -> Option<&'static OceanGrid> {
    static GRID: OnceLock<Option<OceanGrid>> = OnceLock::new();
    GRID.get_or_init(|| {
        if std::env::var("SEAFORGE_OCEAN_GRID").ok().as_deref() == Some("0") {
            return None;
        }
        for path in candidate_paths() {
            if path.exists() {
                match OceanGrid::load(&path) {
                    Ok(grid) => return Some(grid),
                    Err(err) => eprintln!("ocean grid: {err}"),
                }
            }
        }
        None
    })
    .as_ref()
}
